# nginx proxy address - http://172.17.0.1:8110

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  pwndrop:
    image: pwndrop/pwndrop:latest
    container_name: pwndrop-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - pwndrop
    ports:
      - "8110:8110"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/pwndrop:/config
      - ./rootfs/data/pwndrop:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8110"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pwndrop:
    external: false
